services:
  db:
    image: postgres:15-alpine
    container_name: vigilapp_db
    environment:
      POSTGRES_USER: user_an
      POSTGRES_PASSWORD: password_secure_an
      POSTGRES_DB: vigilapp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user_an -d vigilapp_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: vigilapp_main
    ports:
      - "3001:3001"
      - "5173:5173"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user_an:password_secure_an@db:5432/vigilapp_db?schema=public
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
